version: '3.8'

services:
  whiter-app:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    ports:
      - 8000:8000
    volumes:
      - whisper-model:/app
    command: python3 -m flask --debug run

volumes:
  whisper-model: 
    driver: local
