version: '3.8'

services:
  app1: &app1
    container_name: speech_api
    networks:
      - speech
    build:
      dockerfile: Dockerfile
      context: .
      target: production
    # environment:
    #   - GUNICORN_BIND=:8000
    #   - GUNICORN_WORKERS=2
    healthcheck:
      test: curl -o /dev/null -s --retry 0 --head http://localhost:8000/auth/health || exit 1
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: '5GB'
  app2:
    <<: *app1
    container_name: speech_api_2

  load_balancer:
    sysctls:
      net.core.somaxconn: 4096
    container_name: lb
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '128MB'
    networks:
      - speech

volumes:
  whisper-model: 
    driver: local

networks:
  speech: